# NumPy

In [1]:
# Diferencias array - lista

import numpy as np

my_arr = np.arange(1_000_000) # genera un array de un millon de elementos
my_list = list(range(1_000_000)) # genero una lista de un millon de elementos

%timeit my_arr2 = my_arr*2
%timeit my_list2 = my_list*2

# los algoritmos generados con array uelen ser mas veloces

5.31 ms ± 531 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
42.8 ms ± 1.97 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [2]:
# NumPy permite hacer operaciones sobre todos los elementos del array como si se tratara de un valor escalar 

data = np.array([[1.5,-0.1,3],[0,-3,6.5]])
data

array([[ 1.5, -0.1,  3. ],
       [ 0. , -3. ,  6.5]])

In [3]:
data*10

array([[ 15.,  -1.,  30.],
       [  0., -30.,  65.]])

In [4]:
data+data

array([[ 3. , -0.2,  6. ],
       [ 0. , -6. , 13. ]])

In [5]:
# Un ndarray es un conteedor generico multidimensional para datos homogeneos.
# Cada ndarray tiene un shape que indica el tamaño y un dtype que indica el tipo de datos del array

print(data.shape)
print(data.dtype)


(2, 3)
float64


# Creando ndarray

In [6]:
# array(). Esta funcion recibe cualquier objeto parecido a una secuencia y produce un array
data1 = [6,7.5,8,0,1]
print(data1)
print(type(data1))

arr1 = np.array(data1)
print(arr1)
print(type(arr1))

for i in arr1:
    print(i)


[6, 7.5, 8, 0, 1]
<class 'list'>
[6.  7.5 8.  0.  1. ]
<class 'numpy.ndarray'>
6.0
7.5
8.0
0.0
1.0


In [7]:
# array desde una lista anidada
data2 = [[1,2,3,4],[5,6,7,8]]
arr2 = np.array(data2)

#las listas anidadas se convierten en arrays multidimendionales
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [8]:
# existen funciones para crear arrays todos de 0s,1s o sin inicializar
print(np.zeros(4))
print(np.zeros((4,3))) # Cuidado con los parentesis
print(np.ones((3,4)))

print(np.empty((4,4))) # no devuelve 0s,devuelve valores "basura" que se encuentren 
# en memoria

[0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1.69109959e-306 9.34609790e-307 1.33506605e-306 1.86921415e-306]
 [4.45057637e-308 1.37961302e-306 7.56602524e-307 1.24610994e-306]
 [8.45605478e-307 1.37962592e-306 1.42420345e-306 9.79103798e-307]
 [8.90095411e-307 5.48412867e-322 0.00000000e+000 1.94693963e-308]]


In [9]:
#  matriz identidad
print(np.eye(4))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


# Principales tipos de datos en NumPy

In [16]:
arr_int = np.array([1,2,3,4])
print(arr_int.dtype)
arr_float = np.array([1.,2.,3.,4.])
print(arr_float.dtype)
arr_bool = np.array([True,False])
print(arr_bool.dtype)
arr_complex = np.array([1+5j,2+3j])
print(arr_complex.dtype)

# existen mas metodos pero estos son los principales

int32
float64
bool
complex128


In [19]:
# pasar de un tipo a otro de manera explicita
arr_int = np.array([1,2,3,4])
print(arr_int.dtype,arr_int)

arr_mod = arr_int.astype(np.float32)
print(arr_mod.dtype,arr_mod)



int32 [1 2 3 4]
float32 [1. 2. 3. 4.]


# Aritmetica con arrays en NumPy

In [25]:
# Los arrays en NumPy permiten realizar operaciones aritmeticas en todos los
# elementos del array al mismo tiempo. Esto es llamado vectorizacion
# Cualquier operacion aritmetica entre arrays del mismo tamaño se aplica elemento
# por elemento

arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print("---------------------")
print(arr*arr)
print("---------------------")
print(arr+arr)
print("---------------------")
print(arr/arr)
print("---------------------")
# las operaciones con elementos escalares se realizan con todos los elementos
# del arreglo

print(1/arr)
print("---------------------")
print(arr**2)





[[1 2 3]
 [4 5 6]]
---------------------
[[ 1  4  9]
 [16 25 36]]
---------------------
[[ 2  4  6]
 [ 8 10 12]]
---------------------
[[1. 1. 1.]
 [1. 1. 1.]]
---------------------
[[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]
---------------------
[[ 1  4  9]
 [16 25 36]]


In [31]:
# Las comparaciones entre arrays del mismo tamaño producen arrays booleanos
arr2 = np.array([[6,5,4],[3,2,1]])
print(arr)
print("---------------------")
print(arr2)
print("---------------------")
print(arr==arr2)
print("---------------------")
print(arr>arr2)


[[1 2 3]
 [4 5 6]]
---------------------
[[6 5 4]
 [3 2 1]]
---------------------
[[False False False]
 [False False False]]
---------------------
[[False False False]
 [ True  True  True]]


# Indexado

In [42]:
arr = np.array([10,9,8,7,6,5,4,3,2,1,0])
print(arr)

print(arr[0])
print(arr[3])

print(arr[5:8])
arr[5:8] = 20
print(arr)

# cualquier modificacion de la vista se vera reflejada en el array de origen

[10  9  8  7  6  5  4  3  2  1  0]
10
7
[5 4 3]
[10  9  8  7  6 20 20 20  2  1  0]
